//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.TraineeCourses = new HashSet<TraineeCourse>();
        }
        [Required]
        public string TraineeID { get; set; }
        [Required]
        public string TraineeName { get; set; }
        [Required]
        public string userName { get; set; }
        [Required]
        public string ProgramLanguage { get; set; }
        [Required]
        public Nullable<int> TOEIC { get; set; }
        [Required]
        public string Department { get; set; }
        [Required]
        public string Location { get; set; }
        [Required]
        [DisplayName("Date of Birth")]
        public Nullable<System.DateTime> dob { get; set; }
        [Required]
        public string Education { get; set; }
        [Required]
        public Nullable<int> Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeCourse> TraineeCourses { get; set; }
    }
}
