//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainningProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainerTopic
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string TrainerID { get; set; }
        [Required]
        public Nullable<int> TopicID { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
